# cloud-init

package_update: true
package_upgrade: true

manage-resolv-conf: true
resolv_conf:
  nameservers:
    - "8.8.8.8"
    - "8.8.4.4"

users:
  - name: dftfselfagnt
    lock_passwd: true
    shell: /bin/bash
    ssh-authorized-keys:
      - "${ssh_public_key}"
    groups:
      - dftfselfagnt
      - docker
    sudo:
      - ALL=(ALL) NOPASSWD:ALL

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

runcmd:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl start docker
  - systemctl enable docker
  - mkdir /home/dftfselfagnt/myagent && cd /home/dftfselfagnt/myagent
  - wget https://vstsagentpackage.azureedge.net/agent/2.186.1/vsts-agent-linux-x64-2.186.1.tar.gz
  - tar zxvf vsts-agent-linux-x64-2.186.1.tar.gz
  - ./config.sh --unattended --agent "${AZP_AGENT_NAME:-$(hostname)}" --url ${az-devops-url} --auth PAT --token ${pat} --pool ${az-devops-agent-pool} --replace --acceptTeeEula
  - sleep 180
  - sudo ./svc.sh install
  - sudo ./svc.sh start
