#cloud-config

package_update: true
package_upgrade: true

manage-resolv-conf: true
resolv_conf:
  nameservers:
    - "8.8.8.8"
    - "8.8.4.4"

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

runcmd:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=$(dpkg --print-architecture)] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl start docker
  - systemctl enable docker
  - usermod -aG docker agentadm
  - mkdir /home/agentadm/myagent && cd /home/agentadm/myagent
  - wget https://vstsagentpackage.azureedge.net/agent/2.200.2/vsts-agent-linux-x64-2.200.2.tar.gz
  - export AZP_AGENT_NAME=$(hostname)
  - tar -zxvf vsts-agent-linux-x64-2.200.2.tar.gz
  - rm vsts-agent-linux-x64-2.200.2.tar.gz
  - chown -R agentadm:agentadm /home/agentadm/myagent
  - su - agentadm -c "cd /home/agentadm/myagent && ./config.sh --unattended --agent $AZP_AGENT_NAME --url ${az_devops_url} --auth PAT --token ${pat} --pool ${az_devops_agent_pool} --replace --acceptTeeEula $!"
  - sleep 10
  - ./svc.sh install
  - ./svc.sh start
